// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWBs4wucLv22ri2PNzf_zFJ0dDTzJ1AE',
    appId: '1:81201995663:web:137a704673167edc0cf5fa',
    messagingSenderId: '81201995663',
    projectId: 'chat-app-89d9f',
    authDomain: 'chat-app-89d9f.firebaseapp.com',
    storageBucket: 'chat-app-89d9f.firebasestorage.app',
    measurementId: 'G-YJRTS5SLTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZWBs4wucLv22ri2PNzf_zFJ0dDTzJ1AE',
    appId: '1:81201995663:android:137a704673167edc0cf5fa',
    messagingSenderId: '81201995663',
    projectId: 'chat-app-89d9f',
    storageBucket: 'chat-app-89d9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZWBs4wucLv22ri2PNzf_zFJ0dDTzJ1AE',
    appId: '1:81201995663:ios:137a704673167edc0cf5fa',
    messagingSenderId: '81201995663',
    projectId: 'chat-app-89d9f',
    storageBucket: 'chat-app-89d9f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZWBs4wucLv22ri2PNzf_zFJ0dDTzJ1AE',
    appId: '1:81201995663:ios:137a704673167edc0cf5fa',
    messagingSenderId: '81201995663',
    projectId: 'chat-app-89d9f',
    storageBucket: 'chat-app-89d9f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}